apply plugin: "java-library"

jar {
    enabled = true
}

compileJava {
    options.release = 8
}

dependencies {
    implementation("org.apache.hbase:hbase-client")                     { transitive = false }
    implementation("org.apache.hbase:hbase-common")                     { transitive = false }
    implementation("org.apache.hbase:hbase-protocol-shaded")            { transitive = false }
    implementation("org.apache.hbase.thirdparty:hbase-shaded-protobuf") { transitive = false }
    implementation("org.apache.yetus:audience-annotations")             { transitive = false }

    compileOnly("com.google.code.findbugs:annotations")
}

test {
    useJUnitPlatform()
}
