-- start_ignore
-- end_ignore
-- @description query01 for PXF test for cloud access where server is specified, no credentials are specified, and configuration file contains invalid credentials running alongside an HDFS setup
--
-- start_matchsubs
--
-- # create a match/subs
--
-- m/PXF server error.*(doesBucketExist|com.amazonaws).*/
-- s/PXF server error.*/PXF server error : com.amazonaws.services.s3.model.AmazonS3Exception: Invalid credentials/
--
-- m/DETAIL/
-- s/DETAIL/CONTEXT/
--
-- m/CONTEXT:.*line.*/
-- s/line \d* of //g
--
-- m/pxf:\/\/(.*)\/pxf_automation_data/
-- s/pxf:\/\/.*PROFILE/pxf:\/\/pxf_automation_data?PROFILE/
--
-- m/CONTEXT:.*line.*/
-- s/line \d* of //g
--
-- m/CONTEXT:.*External table.*/
-- s/CONTEXT:.*External table.*//
--
-- m/, file.*pxf_automation_data/
-- s/, file.*pxf_automation_data.*/pxf_automation_data/
--
-- end_matchsubs

SELECT *  FROM cloudaccess_server_no_credentials_invalid_config_with_hdfs;
